# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'NewTestCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewTestCode

  target 'NewTestCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewTestCodeUITests' do
    # Pods for testing
  end



end
